FROM arm32v7/debian:10-slim
WORKDIR /app
ENV TMP_NAME=/tmp/dns-proxy-server.tgz
RUN apt-get update && apt-get install --force-yes -y curl
RUN curl -L https://github.com/mageddo/dns-proxy-server/releases/download/2.15.0/dns-proxy-server-linux-arm-2.15.0.tgz > $TMP_NAME && \
	tar -xvf $TMP_NAME -C /app/ && rm -f $TMP_NAME && apt-get purge --force-yes -y curl

LABEL dps.container=true
VOLUME ["/var/run/docker.sock", "/var/run/docker.sock"]
CMD ["bash", "-c", "/app/dns-proxy-server"]
